//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodokanal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ВодоканалEntities2 : DbContext
    {
        static ВодоканалEntities2 _context;
        public static ВодоканалEntities2 GetContext()
        {
            if (_context == null) _context = new ВодоканалEntities2();
            return _context;
        }
        public ВодоканалEntities2()
            : base("name=ВодоканалEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Абонент> Абонент { get; set; }
        public virtual DbSet<Директор> Директор { get; set; }
        public virtual DbSet<Диспетчер> Диспетчер { get; set; }
        public virtual DbSet<Заявка> Заявка { get; set; }
        public virtual DbSet<Лаборатория> Лаборатория { get; set; }
        public virtual DbSet<Показания_счётчиков> Показания_счётчиков { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Проба> Проба { get; set; }
        public virtual DbSet<Сервис_прокладки_труб> Сервис_прокладки_труб { get; set; }
        public virtual DbSet<Техническая_информация> Техническая_информация { get; set; }
        public virtual DbSet<Технический_сотрудник> Технический_сотрудник { get; set; }
        public virtual DbSet<Участок> Участок { get; set; }
    }
}
