//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodokanal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Директор
    {
        public int Id_директора { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int Id_участка { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        public virtual Участок Участок { get; set; }
    }
}
