//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodokanal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        public int Id_заявки { get; set; }
        public int Id_абонента { get; set; }
        public Nullable<int> Id_сотрудника { get; set; }
        public string Текст_заявки { get; set; }
        public string Статус_заявки { get; set; }
        public int Id_участка { get; set; }
    
        public virtual Абонент Абонент { get; set; }
        public virtual Технический_сотрудник Технический_сотрудник { get; set; }
    }
}
