//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodokanal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Показания_счётчиков
    {
        public int Id_абонента { get; set; }
        public double Показания_счётчика_хол__воды { get; set; }
        public double Показания_счётчика_гор__воды { get; set; }
        public System.DateTime Дата_передачи_показаний { get; set; }
        public int Id_показаний { get; set; }
    
        public virtual Абонент Абонент { get; set; }
    }
}
