//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodokanal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Техническая_информация
    {
        public int Id_поставщика { get; set; }
        public System.DateTime Дата_прокладки_труб { get; set; }
        public int Срок_службы__лет { get; set; }
        public int Id_участка { get; set; }
        public int Id_сервиса { get; set; }
    
        public virtual Поставщик Поставщик { get; set; }
        public virtual Сервис_прокладки_труб Сервис_прокладки_труб { get; set; }
        public virtual Участок Участок { get; set; }
    }
}
